nome = str (input("Digite seu nome completo:")).strip()
print ("Analissando seu nome..")
print ("SEU NOME{}".format(nome.upper()))
print ("seu nome{}".format(nome.lower()))
print ("seu nome tem {} letras".format(len(nome)-nome.count(" ")))
print ("seu primeiro nome tem {}letras".format(nome.find(" ")))
separa = nome.split()
print ("seu primeiro nome é {} e ele tem {} letras".format(separa[0], len(separa[0])))